version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - db_questions:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build:
      context: .
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - 5000:8000
    command: bash -c "
      alembic upgrade head &&
      gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
volumes:
  db_questions: